### ISSUE TITLE
Error: ENOENT: no such file or directory, open './build/contracts/Lockdrop.json'

### ISSUE THREAD

**Issue by soc1c** [hicommonwealth/edge-lockdrop#4]
Hi, the lockdrop script does not execute:

```
~/.opt/edge-lockdrop
❯ yarn install
yarn install v1.15.2
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.28s.

~/.opt/edge-lockdrop
❯ node ./scripts/lockdrop.js 
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open './build/contracts/Lockdrop.json'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/home/user/.opt/edge-lockdrop/scripts/lockdrop.js:9:37)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Truffle 5, Node 10, Arch Linux:

```
~/.opt/edge-lockdrop 15s
❯ uname -a
Linux ceres 4.20.13-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 27 19:10:28 UTC 2019 x86_64 GNU/Linux

~/.opt/edge-lockdrop
❯ yarn --version
1.15.2

~/.opt/edge-lockdrop
❯ node --version
v10.15.3

~/.opt/edge-lockdrop
❯ truffle version  
Truffle v5.0.8 (core: 5.0.8)
Solidity v0.5.0 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37
```

**Comment by drewstone** [comment]
Did you run truffle compile? And do you have a local testnet configured?

**Comment by soc1c** [comment]
No, I was following the readme.
